<a href="https://colab.research.google.com/github/jiin124/4th_kaggle_study/blob/main/5%EC%A3%BC%EC%B0%A8/%EC%84%A0%ED%98%95%ED%9A%8C%EA%B7%80_1%EB%B6%80_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports

In [1]:
import torch
import torch.optim as optim



In [2]:
#for reproducibility
torch.manual_seed(1)

## data

In [3]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

In [4]:
print(x_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [5]:
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


## Weight Initialization

In [6]:
#학습용 변수라는 것을 명시
W=torch.zeros(1,requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [7]:
#학습용 변수라는 것을 명시
b=torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


## Weight Initialization

In [8]:
W=torch.zeros(1,requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [9]:
b=torch.zeros(1,requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


## Hypothesis

$$ H(x)=Wx+b $$

In [10]:
hypothesis=x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


## Cost

$$ cost(W,b)=1m∑i=1m(H(x(i))−y(i))2 $$

In [12]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [13]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [14]:
print(hypothesis-y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [15]:
print((hypothesis-y_train**2))

tensor([[-1.],
        [-4.],
        [-9.]], grad_fn=<SubBackward0>)


In [16]:
cost=torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


## Gradient Descent

In [17]:
# learning rate => lr = 0.01
# W := W - alpha*d/dw*cost(w)

optimizer=optim.SGD([W,b],lr=0.01)#경사하강법 방식 SGD(직접 구현도 가능하지만 파이토치에 저장되어있음)

In [18]:
#옵티마이저 초기화
optimizer.zero_grad()

#cost 계산 !!! 미분값 계산해서
cost.backward()
#옵티마이저 갱신
optimizer.step()

In [19]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [20]:
hypothesis=x_train*W+b
print(hypothesis)

tensor([[0.1333],
        [0.2267],
        [0.3200]], grad_fn=<AddBackward0>)


In [21]:
cost=torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(3.6927, grad_fn=<MeanBackward0>)


## Training with full code


In [24]:
# 데이터
X_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[1],[2],[3]])

#모델 초기화
W=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

#optimizer 설정
optimizer=optim.SGD([W,b],lr=0.01)

nb_epochs=1000
for epoch in range(nb_epochs+1):

  #H(x)계산
  hypothesis=x_train*W+b

  #cost 계산
  cost=torch.mean((hypothesis-y_train)**2)

  #cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  #100번마다 로그 출력
  if epoch%100==0:
    print('Epoch {:4d}/{} W:{:.3f}, b: {:.3f} Cost:{:.6f}'.format(
        epoch,nb_epochs,W.item(),b.item(),cost.item()
    ))

Epoch    0/1000 W:0.093, b: 0.040 Cost:4.666667
Epoch  100/1000 W:0.873, b: 0.289 Cost:0.012043
Epoch  200/1000 W:0.900, b: 0.227 Cost:0.007442
Epoch  300/1000 W:0.921, b: 0.179 Cost:0.004598
Epoch  400/1000 W:0.938, b: 0.140 Cost:0.002842
Epoch  500/1000 W:0.951, b: 0.110 Cost:0.001756
Epoch  600/1000 W:0.962, b: 0.087 Cost:0.001085
Epoch  700/1000 W:0.970, b: 0.068 Cost:0.000670
Epoch  800/1000 W:0.976, b: 0.054 Cost:0.000414
Epoch  900/1000 W:0.981, b: 0.042 Cost:0.000256
Epoch 1000/1000 W:0.985, b: 0.033 Cost:0.000158


In [26]:
# H(x) = Wx + b
# 가설설정 => 예측하고자 하는 값 => 시험성적 => 1 * 7 + 0.033 = 

In [25]:
0.985*9+0.033

8.898